version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_PASSWORD: changa
      POSTGRES_USER: changa
      POSTGRES_DB: changa
    volumes:
      - ../../../docker_data/changa-psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
